#ifndef CONFIG_H
#define CONFIG_H

#include "params.h"

#define SEED_LENGTH_PUBLIC_KEY 16
#define SEED_LENGTH_PRIVATE_KEY 32
#define SEED_LENGTH (SEED_LENGTH_PUBLIC_KEY + SEED_LENGTH_PRIVATE_KEY)

#define n_SNOVA  (v_SNOVA + o_SNOVA)
#define m_SNOVA  (o_SNOVA)
#define lsq_SNOVA  (l_SNOVA * l_SNOVA)

#define SIZE_GF16S_SHA3_PUBLIC (lsq_SNOVA * (2 * (lsq_SNOVA + l_SNOVA) + m_SNOVA * (n_SNOVA * n_SNOVA - m_SNOVA * m_SNOVA)))
#define SIZE_GF16S_SHA3_PRIVATE (v_SNOVA*o_SNOVA*l_SNOVA)
#define SIZE_BYTES_SHA3_PUBLIC ((SIZE_GF16S_SHA3_PUBLIC + 1) >> 1)
#define SIZE_BYTES_SHA3_PRIVATE (SEED_LENGTH_PUBLIC_KEY + ((SIZE_GF16S_SHA3_PRIVATE + 1) >> 1))

#define SIZE_GF16S_HASH (o_SNOVA * lsq_SNOVA)
#define SIZE_GF16S_SIGNATURE (n_SNOVA * lsq_SNOVA)
#define SIZE_BYTE_HASH ((SIZE_GF16S_HASH + 1) >> 1)

#define RANK (l_SNOVA)
#define RANK_SQ (RANK * RANK)

#define SIZE_BYTES_PK (SEED_LENGTH_PUBLIC_KEY + ((m_SNOVA * o_SNOVA * o_SNOVA * lsq_SNOVA + 1) >> 1))
#define SIZE_BYTES_SK (((lsq_SNOVA * (4 * lsq_SNOVA + (m_SNOVA * v_SNOVA * v_SNOVA + m_SNOVA * v_SNOVA * o_SNOVA + m_SNOVA * o_SNOVA * v_SNOVA) + v_SNOVA * o_SNOVA) + 1) >> 1) + SEED_LENGTH_PUBLIC_KEY + SEED_LENGTH_PRIVATE_KEY)

#define SIZE_BYTES_SIGNATURE ((SIZE_GF16S_SIGNATURE + 1) >> 1)
#define BYTES_SALT 16

#define SIZE_GF16S_PRNG_PUBLIC (lsq_SNOVA * (2 * (lsq_SNOVA + l_SNOVA) + m_SNOVA * (n_SNOVA * n_SNOVA - m_SNOVA * m_SNOVA)))
#define SIZE_GF16S_PRNG_PRIVATE (v_SNOVA * o_SNOVA * l_SNOVA)
#define SIZE_BYTES_PRNG_PUBLIC ((SIZE_GF16S_PRNG_PUBLIC + 1) >> 1)
#define SIZE_BYTES_PRNG_PRIVATE ((SIZE_GF16S_PRNG_PRIVATE + 1) >> 1)

#endif
